### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by vvenla** [TainaLepisto/HunajaPurkki#1]
Projektia tarkasteltu 3.1. klo 10:45

Dokumentaatio on kattavaa ja siististi tehty. Käsite- ja relaatiokaavioita sai kuitenkin tuijotella hetken ennen kuin niistä sai selvää. Voisi auttaa hahmottamaan, jos molemmat olisi tehty suunnilleen samalla formaatilla. Lisäksi hämmensi se, että käsitekaaviossa pesän ja muistutuksen välillä ei ollut monesta moneen -suhdetta, mutta relaatiokaavioon oli kuitenkin laitettu niiden välille liitostaulu. Käsitekaaviosta näyttäisi siten puuttuvan projektin vaatimuksissakin ollut monesta moneen -suhde kokonaan.

Voisi myös miettiä, kannattaisiko tietokantaa normalisoida ja poistaa ylimääräisiä yhteyksiä.

Testidataa olisi kaivannut hieman lisää.

Projekti vaikuttaa kuitenkin toimivalta, ja näkymien ulkoasu on tyylikäs ja toimiva. Koodissa on käytetty Clean code -periaatteita.

**Comment by TainaLepisto** [comment]
Kiitos kommenteista. Olisiko jotain ajatusta miten tietokantaa kannattaisi muokata? 

Ja monen suhde moneen tosiaan puuttui aluksi ja lisäsin sen myöhemmin lennosta mukaan. Päivitän tuon käsitekaavion selkeämmäksi.

**Comment by vvenla** [comment]
En tiedä kuinka asiantuntevia ajatuksia osaan antaa tietokannan muokkauksesta, mutta jäin siis miettimään ovatko kaikki yhteydet taulujen välillä välttämättömiä? Luokkakaavion mukaan pesä liittyy aina yhteen tarhaan, jolla on yksi mehiläistarhaaja, jolloin ei tarvittaisi enää erikseen yhteyttä tarhaajan ja pesän välillä. Huomasin kuitenkin nyt, että relaatiokaavioon oli lisätty myös vaihtoehto, että pesällä ei olisi yhtään tarhaa, jolloin se tietenkin tarvitsee yhteyden tarhaajaan. Tuntuisi kuitenkin ehkä loogisemmalta (ja helpommalta toteutuksen kannalta), jos jo yksi pesä voisi muodostaa oman tarhansa, jolla sitten on oma tarhaajansa.

Sama pohdinta koski myös yhteyttä kuningattaren ja mehiläistarhaajan välillä.

On toki hyvin mahdollista, etten ole ymmärtänyt kaikkien yhteyksien tarkoitusta, mutta tässä ajatuksiani. Ja tosiaan dokumentissa on pieniä ristiriitaisuuksia käyttötapauskuvausten, luokkakaavion ja relaatiokaavion välillä, jotka hankaloittavat hahmotusta näin ulkopuolisen silmin. Muuten tosiaan vaikutti oikein hyvältä!
